"""create training weeks table

Revision ID: 9e60146df5b9
Revises: 649410882fa6
Create Date: 2026-08-09 12:50:34.239832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e60146df5b9'
down_revision: Union[str, Sequence[str], None] = '649410882fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_block_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('focus', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['training_block_id'], ['training_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_weeks_id'), 'training_weeks', ['id'], unique=False)
    op.create_index(op.f('ix_training_weeks_training_block_id'), 'training_weeks', ['training_block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_weeks_training_block_id'), table_name='training_weeks')
    op.drop_index(op.f('ix_training_weeks_id'), table_name='training_weeks')
    op.drop_table('training_weeks')
    # ### end Alembic commands ###
